export const blogPosts = [
  {
    slug: "shopify-product-image-guide",
    title: "The Ultimate Shopify Product Image Guide for 2024",
    excerpt: "Learn the exact image sizes, formats, and best practices that will make your Shopify store convert better.",
    category: "Shopify",
    author: "Sarah K.",
    date: "2024-11-15",
    readTime: "8 min read",
    emoji: "🛍️",
  },
  {
    slug: "amazon-product-photo-requirements",
    title: "Amazon Product Photography Requirements: Everything You Need to Know",
    excerpt: "Amazon's image requirements are strict. Here's how to get your products approved and ranking higher.",
    category: "Amazon",
    author: "Mike T.",
    date: "2024-11-10",
    readTime: "6 min read",
    emoji: "📦",
  },
  {
    slug: "remove-background-product-photos",
    title: "How to Remove Backgrounds from Product Photos (Free)",
    excerpt: "Step-by-step guide to removing backgrounds from your product images without Photoshop or paying for software.",
    category: "Image Optimization",
    author: "Jenny L.",
    date: "2024-11-05",
    readTime: "5 min read",
    emoji: "✂️",
  },
  {
    slug: "etsy-image-optimization",
    title: "Etsy Image Optimization: How to Get More Clicks",
    excerpt: "Your Etsy listing image is the single most important factor for clicks. Here's how to optimize it.",
    category: "Etsy",
    author: "Sarah K.",
    date: "2024-10-30",
    readTime: "7 min read",
    emoji: "🎨",
  },
  {
    slug: "webp-vs-jpg-ecommerce",
    title: "WEBP vs JPG for E-commerce: Which Format is Better?",
    excerpt: "Choosing the right image format can impact your page speed and SEO. Here's a complete breakdown.",
    category: "SEO",
    author: "Mike T.",
    date: "2024-10-20",
    readTime: "6 min read",
    emoji: "⚡",
  },
  {
    slug: "ai-product-photography-guide",
    title: "AI Product Photography: Can It Replace a Real Photoshoot?",
    excerpt: "We tested AI-generated product photos against traditional studio shoots. The results surprised us.",
    category: "Product Photography",
    author: "Jenny L.",
    date: "2024-10-15",
    readTime: "10 min read",
    emoji: "🤖",
  },
  {
    slug: "tiktok-shop-image-requirements",
    title: "TikTok Shop Image Requirements & Best Practices",
    excerpt: "TikTok Shop is growing fast. Make sure your product images meet the requirements to go live.",
    category: "Marketplace Guides",
    author: "Sarah K.",
    date: "2024-10-08",
    readTime: "5 min read",
    emoji: "🎵",
  },
  {
    slug: "compress-images-without-quality-loss",
    title: "How to Compress Product Images Without Losing Quality",
    excerpt: "Large images slow down your store and hurt SEO. Here's how to compress them without visible quality loss.",
    category: "Image Optimization",
    author: "Mike T.",
    date: "2024-09-25",
    readTime: "6 min read",
    emoji: "🗜️",
  },
];

export const categories = [
  "All",
  "Shopify",
  "Amazon",
  "Etsy",
  "Product Photography",
  "Marketplace Guides",
  "SEO",
  "Image Optimization",
];
